server:
  port: 9999
  servlet:
    context-path: /nice-api
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: nice-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vip?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '123456'
    driver-class-name: com.mysql.jdbc.Driver


